CREATE OR REPLACE PACKAGE BODY FUN_ADMINISTRADOR AS

PROCEDURE INSERTAR_RAZA
  (DESCRIPCION IN VARCHAR,TIPO1 IN VARCHAR) AS
  BEGIN
    INSERT INTO RAZA(ID_RAZA, DESCRIPCION_RAZA, TIPO_MASCOTA)
    VALUES(S_RAZA.NEXTVAL,DESCRIPCION, TIPO1);
    COMMIT;
    
END INSERTAR_RAZA;
END FUN_ADMINISTRADOR;
