CREATE OR REPLACE PACKAGE BODY CONSULTAS AS

FUNCTION VALIDA_USUARIO(USUARIO1 IN VARCHAR2, CONTRASENA IN VARCHAR)
 RETURN BOOLEAN
 IS EXISTE BOOLEAN;
 BEGIN
   SELECT * 
   INTO EXISTE

   FROM USUARIO
   WHERE EXISTS
          (SELECT * 
           FROM USUARIO U
           WHERE U.USER_NAME = USUARIO1 AND U.CONTRASEÑA = 'ALE');

  RETURN(EXISTE);
  END;


END CONSULTAS;
