CREATE OR REPLACE PACKAGE BODY CONSULTAS AS

FUNCTION VALIDA_USUARIO(USUARIO1 IN VARCHAR2, CONTRASENA IN VARCHAR2)
  RETURN TYPES.ref_c
  AS valida TYPES.ref_c;
  BEGIN
    OPEN valida FOR
    select U.id_usuario
    FROM USUARIO U
    WHERE U.USER_NAME = USUARIO1 AND U.CONTRASEÑA = contrasena;
   return valida;
  exception
    when NO_DATA_FOUND then
         DBMS_OUTPUT.PUT_LINE('NO EXISTE');

   END VALIDA_USUARIO;

END CONSULTAS;
