CREATE OR REPLACE PACKAGE BODY CONSULTAS AS

FUNCTION VALIDA_USUARIO(USUARIO1 IN VARCHAR2, CONTRASENA IN VARCHAR2)
  RETURN TYPES.ref_c
  AS valida TYPES.ref_c;
  BEGIN
    OPEN valida FOR
    select U.id_usuario
    FROM USUARIO U
    WHERE U.USER_NAME = USUARIO1 AND U.CONTRASEÑA = contrasena;
   return valida;
  exception
    when NO_DATA_FOUND then
         DBMS_OUTPUT.PUT_LINE('NO EXISTE');

   END VALIDA_USUARIO;
   
FUNCTION INFO_PER_CASACUNA
  RETURN TYPES.ref_c
  AS INFORMA TYPES.ref_c;
  BEGIN
    OPEN INFORMA FOR
    SELECT U.NOMBRE, U.APELLIDO1, U.APELLIDO2, U.CALIFICACION,
           D.PROVINCIA,D.CANTON,D.DIRECCION_EXACTA,CC.TAMANO,
           CC.REQUIERE_ALIMENTO, E.VALOR_EMAIL, T.TELEFONO

    FROM CASA_CUNA CC, USUARIO U, DIRECCION D, EMAIL E, TELEFONO T

    WHERE U.ID_USUARIO = CC.ID_PERSONA 
    AND D.ID_DIRECCION = U.ID_USUARIO
    AND D.TIPO_DIREC = U.TIPO
    AND E.ID_EMAIL = CC.ID_PERSONA
    AND E.TIPO_EMAIL = U.TIPO
    AND T.ID_TEL = CC.ID_PERSONA
    AND T.TIPO_TEL = U.TIPO;
    RETURN INFORMA;
 
 END INFO_PER_CASACUNA;

END CONSULTAS;

