--roll
CREATE USER AD 
IDENTIFIED BY ad 
DEFAULT TABLESPACE ad_data 
QUOTA 10M ON ad_data 
TEMPORARY TABLESPACE temp
QUOTA 5M ON system;

create ROLE RAD
IDENTIFIED BY ad;

GRANT CONNECT to ad;

