SELECT U.NOMBRE, U.APELLIDO1, U.APELLIDO2, U.CALIFICACION,
D.PROVINCIA,D.CANTON,D.DIRECCION_EXACTA,CC.TAMANO,CC.REQUIERE_ALIMENTO

FROM CASA_CUNA CC, USUARIO U, DIRECCION D

WHERE U.ID_USUARIO = CC.ID_PERSONA 
and D.ID_DIRECCION = U.ID_USUARIO
and D.TIPO_DIREC = U.TIPO
