SELECT U.NOMBRE, U.APELLIDO1, U.APELLIDO2, U.CALIFICACION,
D.PROVINCIA,D.CANTON,D.DIRECCION_EXACTA,CC.TAMANO,CC.REQUIERE_ALIMENTO, E.VALOR_EMAIL, T.TELEFONO

FROM CASA_CUNA CC, USUARIO U, DIRECCION D, EMAIL E, TELEFONO T

WHERE U.ID_USUARIO = CC.ID_PERSONA 
AND D.ID_DIRECCION = U.ID_USUARIO
AND D.TIPO_DIREC = U.TIPO
AND E.ID_EMAIL = CC.ID_PERSONA
AND E.TIPO_EMAIL = U.TIPO
AND T.ID_TEL = CC.ID_PERSONA
AND T.TIPO_TEL = U.TIPO
