SELECT e.ESTADO_ENC, e.ID_MASCOTA_ENC, e.NOMBRE_ENC, e.TAMANO_ENC, e.COLOR_ENC, e.CHIP_IDENTIFICACION_ENC, p.ESTADO_PER, p.ID_MASCOTA_PER, p.NOMBRE_PER, p.TAMANO_PER, p.COLOR_PER, P.USUARIO_REGISTRA_PER
FROM MASCOTA_PERDIDA P, MASCOTA_ENCONTRADA E, RAZA R
WHERE P.TAMANO_PER = E.TAMANO_ENC AND P.TIPO_Y_RAZA_PER = E.TIPO_Y_RAZA_ENC and p.COLOR_PER = e.COLOR_ENC and E.TIPO_Y_RAZA_ENC = R.ID_RAZA and P.TIPO_Y_RAZA_PER= R.ID_RAZA
