/* 
SELECT *
FROM MASCOTA_PERDIDA P, MASCOTA_ENCONTRADA E, RAZA R, DIRECCION D
WHERE P.TAMANO_PER = E.TAMANO_ENC 
      AND P.TIPO_Y_RAZA_PER = E.TIPO_Y_RAZA_ENC 
      AND p.COLOR_PER = E.COLOR_ENC  
      AND P.TIPO_Y_RAZA_PER= R.ID_RAZA
      AND P.ID_MASCOTA_PER = D.ID_DIRECCION*/
   
CREATE OR REPLACE FUNCTION MATCH2
  RETURN TYPES.ref_c
  AS match1 TYPES.ref_c;
  BEGIN
    OPEN match1 FOR
    SELECT *
    FROM MASCOTA_PERDIDA P, MASCOTA_ENCONTRADA E, RAZA R, DIRECCION D
    WHERE P.TAMANO_PER = E.TAMANO_ENC 
      AND P.TIPO_Y_RAZA_PER = E.TIPO_Y_RAZA_ENC 
      AND p.COLOR_PER = E.COLOR_ENC  
      AND P.TIPO_Y_RAZA_PER= R.ID_RAZA
      AND P.ID_MASCOTA_PER = D.ID_DIRECCION;
    RETURN match1;
 END MATCH2;
