-- join por lugar--

-- por canton--

SELECT C.NOMBRE,C.ESTADO,D.PAIS,D.PROVINCIA,D.CANTON,D.DISTRITO,D.DIRECCION_EXACTA, C.FECHA_INGRESO
FROM MASCOTA C, DIRECCION D
WHERE C.ID_MASCOTA = D.ID_DIRECCION and like CONCAT(pAutor, '%')
ORDER BY C.FECHA_INGRESO DESC
      
-- por Procinvicia

SELECT C.NOMBRE,C.ESTADO,D.PAIS,D.PROVINCIA,D.CANTON,D.DISTRITO,D.DIRECCION_EXACTA, C.FECHA_INGRESO
FROM MASCOTA C, DIRECCION D
WHERE C.ID_MASCOTA = D.ID_DIRECCION and like CONCAT(pAutor, '%')
ORDER BY C.FECHA_INGRESO DESC

-- Distrito

SELECT C.NOMBRE,C.ESTADO,D.PAIS,D.PROVINCIA,D.CANTON,D.DISTRITO,D.DIRECCION_EXACTA, C.FECHA_INGRESO
FROM MASCOTA C, DIRECCION D
WHERE C.ID_MASCOTA = D.ID_DIRECCION and D.Distrito 
ORDER BY C.FECHA_INGRESO DESClike CONCAT(pAutor, '%')


-- Búsquedas por chip

SELECT C.NOMBRE,C.ESTADO,D.PAIS,D.PROVINCIA,D.CANTON,D.DISTRITO,D.DIRECCION_EXACTA, C.FECHA_INGRESO
FROM MASCOTA C, DIRECCION D
WHERE C.ID_MASCOTA = D.ID_DIRECCION and C.CHIP_IDENTIFICACION like CONCAT(pAutor, '%')
ORDER BY C.FECHA_INGRESO DESC

