-- join por lugar--

-- por canton--

SELECT C.NOMBRE,C.ESTADO,D.PAIS,D.PROVINCIA,D.CANTON,D.DISTRITO,D.DIRECCION_EXACTA, C.FECHA_INGRESO
FROM MASCOTA C, DIRECCION D
WHERE C.ID_MASCOTA = D.ID_DIRECCION and like CONCAT(pAutor, '%')
ORDER BY C.FECHA_INGRESO DESC
      
-- por Procinvicia

SELECT C.NOMBRE,C.ESTADO,D.PAIS,D.PROVINCIA,D.CANTON,D.DISTRITO,D.DIRECCION_EXACTA, C.FECHA_INGRESO
FROM MASCOTA C, DIRECCION D
WHERE C.ID_MASCOTA = D.ID_DIRECCION and like CONCAT(pAutor, '%')
ORDER BY C.FECHA_INGRESO DESC

-- Distrito

SELECT C.NOMBRE,C.ESTADO,D.PAIS,D.PROVINCIA,D.CANTON,D.DISTRITO,D.DIRECCION_EXACTA, C.FECHA_INGRESO
FROM MASCOTA C, DIRECCION D
WHERE C.ID_MASCOTA = D.ID_DIRECCION and D.Distrito 
ORDER BY C.FECHA_INGRESO DESClike CONCAT(pAutor, '%')


-- Búsquedas por chip

SELECT C.NOMBRE,C.ESTADO,D.PAIS,D.PROVINCIA,D.CANTON,D.DISTRITO,D.DIRECCION_EXACTA, C.FECHA_INGRESO
FROM MASCOTA C, DIRECCION D
WHERE C.ID_MASCOTA = D.ID_DIRECCION and C.CHIP_IDENTIFICACION like CONCAT(32, '%')
ORDER BY C.FECHA_INGRESO DESC

-- Búsquedas por estado

SELECT C.NOMBRE,C.ESTADO,D.PAIS,D.PROVINCIA,D.CANTON,D.DISTRITO,D.DIRECCION_EXACTA, C.FECHA_INGRESO
FROM MASCOTA C, DIRECCION D
WHERE C.ID_MASCOTA = D.ID_DIRECCION and C.ESTADO like CONCAT('E', '%')
ORDER BY C.FECHA_INGRESO DESC

-- Búsquedas por tipo mascota

SELECT C.NOMBRE,C.ESTADO, R.DESCRIPCION_RAZA, R.TIPO_MASCOTA, D.PAIS,D.PROVINCIA,D.CANTON,D.DISTRITO,D.DIRECCION_EXACTA, C.FECHA_INGRESO
FROM MASCOTA C, DIRECCION D, RAZA R
WHERE R.TIPO_MASCOTA  like CONCAT('Perro', '%') and c.tipo_y_raza = r.id_raza and c.id_mascota = d.id_direccion
ORDER BY C.FECHA_INGRESO DESC

-- Búsquedas por raza

SELECT C.NOMBRE,C.ESTADO, R.DESCRIPCION_RAZA, R.TIPO_MASCOTA, D.PAIS,D.PROVINCIA,D.CANTON,D.DISTRITO,D.DIRECCION_EXACTA, C.FECHA_INGRESO
FROM MASCOTA C, DIRECCION D, RAZA R
WHERE R.DESCRIPCION_RAZA like CONCAT('Golden', '%') and c.tipo_y_raza = r.id_raza and c.id_mascota = d.id_direccion
ORDER BY C.FECHA_INGRESO DESC


